### ISSUE TITLE
Scraper not working

### ISSUE THREAD

**Issue by WouterDX** [thomaswilburn/journalism-js#1]
Hi Thomas, 

I was browsing your repos to find some introductory stuff that's both Javascript and Journalism, and wanted to test your scraper code. For some reason it's not working for me, if I type node.scraper I get this error: 
`TypeError: Cannot set property length of [object Object] which has only a getter
    at new NodeList (F:\onlinecourse\journalism_js\journalism-js-master\scraping-by\node_modules\jsdom\lib\jsdom\level1\core.js:172:28)
    at HTMLDocument.dom.Document.querySelectorAll (F:\onlinecourse\journalism_js\journalism-js-master\scraping-by\node_modules\jsdom\lib\jsdom\selectors\index.js:17:12)
    at Request._callback (F:\onlinecourse\journalism_js\journalism-js-master\scraping-by\scraper.js:19:24)
    at Request.self.callback (F:\onlinecourse\journalism_js\journalism-js-master\scraping-by\node_modules\request\request.js:188:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (F:\onlinecourse\journalism_js\journalism-js-master\scraping-by\node_modules\request\request.js:1171:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (F:\onlinecourse\journalism_js\journalism-js-master\scraping-by\node_modules\request\request.js:1091:12)`.

Perhaps it's just the case of the website being broken, I don't know. 
By the way, if there are other available tutorials/examples/course materials that you recommend for data journalism with actual software like angular, I would definitely be interested.

I'll fiddle around with the scraper and let you know if I understand what's wrong, but so far I'm too noob to get it.

**Comment by thomaswilburn** [comment]
Hey, sorry about that. The dependencies for that script worked well on an older version of Node, but new versions (and new JSDOM) versions seem to have broken it. I just pushed up a version that uses the `cheerio` package instead of JSDOM, and it should work for you now. Give it a shot, and hopefully at some point I'll update the readme to match (or feel free to submit a PR with changes).

**Comment by WouterDX** [comment]
Wow, that was quick, thanks.
